In [1]:
# Import required libraries
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [2]:

from pandas import  *
from numpy import *
from seaborn import *
from matplotlib.pyplot import *
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import MinMaxScaler

In [3]:
df=read_csv('Solarsysplanets.csv')

In [4]:
df

,planet,mass,diameter,density,gravity,escape_velocity,rotation_period,length_of_day,distance_from_sun,perihelion,...,orbital_period,orbital_velocity,orbital_inclination,orbital_eccentricity,obliquity_to_orbit,mean_temperature,surface_pressure,number_of_moons,has_ring_system,has_global_magnetic_field
0,Small rocky hot(Mercury),0.3300,4879,5427,3.7,4.3,1407.6,4222.6,57.9,46.0,...,88.0,47.4,7.0,0.205,0.034,167,0,0,0,1
1,Cloudy volcanic hot(Venus),4.8700,12104,5243,8.9,10.4,-5832.5,2802.0,108.2,107.5,...,224.7,35.0,3.4,0.007,177.400,464,92,0,0,0
2,Blue water world(Earth),5.9700,12756,5514,9.8,11.2,23.9,24.0,149.6,147.1,...,365.2,29.8,0.0,0.017,23.400,15,1,1,0,1
3,Red dusty small(Mars),0.6420,6792,3933,3.7,5.0,24.6,24.7,227.9,206.6,...,687.0,24.1,1.9,0.094,25.200,-65,0.01,2,0,0
4,Giant stormy gas giant(Jupiter),1898.0000,142984,1326,23.1,59.5,9.9,9.9,778.6,740.5,...,4331.0,13.1,1.3,0.049,3.100,-110,Unk0wn*,79,1,1
5,Ringed giant gas majestic(Saturn),568.0000,120536,687,9.0,35.5,10.7,10.7,1433.5,1352.6,...,10747.0,9.7,2.5,0.057,26.700,-140,Unk0wn*,62,1,1
6,Ice tilted big blue-green(Uranus),86.8000,51118,1271,8.7,21.3,-17.2,17.2,2872.5,2741.3,...,30589.0,6.8,0.8,0.046,97.800,-195,Unk0wn*,27,1,1
7,Blue windy big(Neptune),102.0000,49528,1638,11.0,23.5,16.1,16.1,4495.1,4444.5,...,59800.0,5.4,1.8,0.011,28.300,-200,Unk0wn*,14,1,1
8,Dwarf icy tiny(Pluto),0.0146,2370,2095,0.7,1.3,-153.3,153.3,5906.4,4436.8,...,90560.0,4.7,17.2,0.244,122.500,-225,0.00001,5,0,0

In [5]:
df=df.drop(columns='surface_pressure')
df

,planet,mass,diameter,density,gravity,escape_velocity,rotation_period,length_of_day,distance_from_sun,perihelion,aphelion,orbital_period,orbital_velocity,orbital_inclination,orbital_eccentricity,obliquity_to_orbit,mean_temperature,number_of_moons,has_ring_system,has_global_magnetic_field
0,Small rocky hot(Mercury),0.3300,4879,5427,3.7,4.3,1407.6,4222.6,57.9,46.0,69.8,88.0,47.4,7.0,0.205,0.034,167,0,0,1
1,Cloudy volcanic hot(Venus),4.8700,12104,5243,8.9,10.4,-5832.5,2802.0,108.2,107.5,108.9,224.7,35.0,3.4,0.007,177.400,464,0,0,0
2,Blue water world(Earth),5.9700,12756,5514,9.8,11.2,23.9,24.0,149.6,147.1,152.1,365.2,29.8,0.0,0.017,23.400,15,1,0,1
3,Red dusty small(Mars),0.6420,6792,3933,3.7,5.0,24.6,24.7,227.9,206.6,249.2,687.0,24.1,1.9,0.094,25.200,-65,2,0,0
4,Giant stormy gas giant(Jupiter),1898.0000,142984,1326,23.1,59.5,9.9,9.9,778.6,740.5,816.6,4331.0,13.1,1.3,0.049,3.100,-110,79,1,1
5,Ringed giant gas majestic(Saturn),568.0000,120536,687,9.0,35.5,10.7,10.7,1433.5,1352.6,1514.5,10747.0,9.7,2.5,0.057,26.700,-140,62,1,1
6,Ice tilted big blue-green(Uranus),86.8000,51118,1271,8.7,21.3,-17.2,17.2,2872.5,2741.3,3003.6,30589.0,6.8,0.8,0.046,97.800,-195,27,1,1
7,Blue windy big(Neptune),102.0000,49528,1638,11.0,23.5,16.1,16.1,4495.1,4444.5,4545.7,59800.0,5.4,1.8,0.011,28.300,-200,14,1,1
8,Dwarf icy tiny(Pluto),0.0146,2370,2095,0.7,1.3,-153.3,153.3,5906.4,4436.8,7375.9,90560.0,4.7,17.2,0.244,122.500,-225,5,0,0

In [6]:
df.shape

(9, 20)

In [7]:
x=df.iloc[:,1:20]
x

,mass,diameter,density,gravity,escape_velocity,rotation_period,length_of_day,distance_from_sun,perihelion,aphelion,orbital_period,orbital_velocity,orbital_inclination,orbital_eccentricity,obliquity_to_orbit,mean_temperature,number_of_moons,has_ring_system,has_global_magnetic_field
0,0.3300,4879,5427,3.7,4.3,1407.6,4222.6,57.9,46.0,69.8,88.0,47.4,7.0,0.205,0.034,167,0,0,1
1,4.8700,12104,5243,8.9,10.4,-5832.5,2802.0,108.2,107.5,108.9,224.7,35.0,3.4,0.007,177.400,464,0,0,0
2,5.9700,12756,5514,9.8,11.2,23.9,24.0,149.6,147.1,152.1,365.2,29.8,0.0,0.017,23.400,15,1,0,1
3,0.6420,6792,3933,3.7,5.0,24.6,24.7,227.9,206.6,249.2,687.0,24.1,1.9,0.094,25.200,-65,2,0,0
4,1898.0000,142984,1326,23.1,59.5,9.9,9.9,778.6,740.5,816.6,4331.0,13.1,1.3,0.049,3.100,-110,79,1,1
5,568.0000,120536,687,9.0,35.5,10.7,10.7,1433.5,1352.6,1514.5,10747.0,9.7,2.5,0.057,26.700,-140,62,1,1
6,86.8000,51118,1271,8.7,21.3,-17.2,17.2,2872.5,2741.3,3003.6,30589.0,6.8,0.8,0.046,97.800,-195,27,1,1
7,102.0000,49528,1638,11.0,23.5,16.1,16.1,4495.1,4444.5,4545.7,59800.0,5.4,1.8,0.011,28.300,-200,14,1,1
8,0.0146,2370,2095,0.7,1.3,-153.3,153.3,5906.4,4436.8,7375.9,90560.0,4.7,17.2,0.244,122.500,-225,5,0,0

In [8]:
y=df[['planet']]

In [9]:
y

                              planet
0           Small rocky hot(Mercury)
1         Cloudy volcanic hot(Venus)
2           Blue  water world(Earth)
3              Red dusty small(Mars)
4    Giant stormy gas giant(Jupiter)
5  Ringed giant gas majestic(Saturn)
6  Ice tilted big blue-green(Uranus)
7            Blue windy big(Neptune)
8              Dwarf icy tiny(Pluto)

In [10]:
'''from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=1)
'''

'from sklearn.model_selection import train_test_split\nx_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=1)\n'

In [11]:
from sklearn.ensemble import RandomForestClassifier
r=RandomForestClassifier(n_estimators=200,random_state=1)

In [12]:
r.fit(x,y)

C:\Users\debna\AppData\Local\Temp\ipykernel_8744\2591809438.py:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  r.fit(x,y)

RandomForestClassifier(n_estimators=200, random_state=1)

In [13]:
r.score(x,y)

1.0

In [15]:
pred=r.predict([[0.014,2350,2100,0.6,1.5,-150,150,5900,4440,7380.9,90500,4.6,17,0.2,122,-220,4,0,0]])

c:\Users\debna\anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

In [16]:
pred

array(['Dwarf icy tiny(Pluto)'], dtype=object)