In [43]:

from pandas import  *
from numpy import *
from seaborn import *
from matplotlib.pyplot import *
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import MinMaxScaler

In [44]:
# Import required libraries
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [45]:
df=read_csv('IsPattern.csv')

In [46]:
df

    Column1   Column2  Column3  Column4  IsInPattern
0          0        1        2        3            1
1          2        3        4        5            1
2          3        4        5        6            1
3          4        5        6        7            1
4          5        6        7        8            1
5          6        7        8        9            1
6          0        2        4        6            1
7          1        3        5        7            1
8          2        4        6        8            1
9          3        5        7        9            1
10         0        3        6        9            1
11         0        3        6        7            0
12         1        2        4        6            0
13         2        3        5        7            0
14         3        5        7        8            0
15         1        2        4        6            0
16         1        2        4        7            0
17         2        3        5        7            0
18         2        3        5        8            0
19         3        5        7        8            0
20         3        5        6        9            0
21         4        5        7        9            0
22         4        5        6        9            0
23         5        6        8        9            0
24         5        7        8        9            0
25         6        7        8        9            1
26         2        3        4        6            0
27         2        3        7        8            0
28         2        4        6        7            0
29         3        4        6        7            0
30         1        2        8        9            0
31         1        2        7        9            0

In [47]:
x=df.iloc[: ,0:4]

In [48]:
x

    Column1   Column2  Column3  Column4
0          0        1        2        3
1          2        3        4        5
2          3        4        5        6
3          4        5        6        7
4          5        6        7        8
5          6        7        8        9
6          0        2        4        6
7          1        3        5        7
8          2        4        6        8
9          3        5        7        9
10         0        3        6        9
11         0        3        6        7
12         1        2        4        6
13         2        3        5        7
14         3        5        7        8
15         1        2        4        6
16         1        2        4        7
17         2        3        5        7
18         2        3        5        8
19         3        5        7        8
20         3        5        6        9
21         4        5        7        9
22         4        5        6        9
23         5        6        8        9
24         5        7        8        9
25         6        7        8        9
26         2        3        4        6
27         2        3        7        8
28         2        4        6        7
29         3        4        6        7
30         1        2        8        9
31         1        2        7        9

In [49]:
y=df[['IsInPattern']]

In [50]:
y

    IsInPattern
0             1
1             1
2             1
3             1
4             1
5             1
6             1
7             1
8             1
9             1
10            1
11            0
12            0
13            0
14            0
15            0
16            0
17            0
18            0
19            0
20            0
21            0
22            0
23            0
24            0
25            1
26            0
27            0
28            0
29            0
30            0
31            0

In [51]:

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [52]:

'''# Standardize the data
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Build the ANN model
model = Sequential()
model.add(Dense(units=512, activation='relu', input_dim=4))
model.add(Dense(units=128, activation='relu'))
model.add(Dense(units=64, activation='relu'))
model.add(Dense(units=32, activation='relu'))
model.add(Dense(units=8, activation='relu'))
model.add(Dense(units=1, activation='sigmoid'))

# Compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Train the model
model.fit(X_train_scaled, y_train, epochs=15, batch_size=1, validation_data=(X_test_scaled, y_test))
'''

"# Standardize the data\nscaler = StandardScaler()\nX_train_scaled = scaler.fit_transform(X_train)\nX_test_scaled = scaler.transform(X_test)\n\n# Build the ANN model\nmodel = Sequential()\nmodel.add(Dense(units=512, activation='relu', input_dim=4))\nmodel.add(Dense(units=128, activation='relu'))\nmodel.add(Dense(units=64, activation='relu'))\nmodel.add(Dense(units=32, activation='relu'))\nmodel.add(Dense(units=8, activation='relu'))\nmodel.add(Dense(units=1, activation='sigmoid'))\n\n# Compile the model\nmodel.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])\n\n# Train the model\nmodel.fit(X_train_scaled, y_train, epochs=15, batch_size=1, validation_data=(X_test_scaled, y_test))\n"

In [94]:
from keras.layers import LeakyReLU

# Standardize the data
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Build the ANN model
model = Sequential()
model.add(Dense(units=256, input_dim=4))
model.add(LeakyReLU(alpha=0.1))
model.add(Dense(units=128))
model.add(LeakyReLU(alpha=0.1))
model.add(Dense(units=64))
model.add(LeakyReLU(alpha=0.1))
model.add(Dense(units=8))
model.add(LeakyReLU(alpha=0.1))
model.add(Dense(units=2))
model.add(LeakyReLU(alpha=0.1))
model.add(Dense(units=1, activation='sigmoid'))

# Compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Train the model
model.fit(X_train_scaled, y_train, epochs=20, batch_size=1, validation_data=(X_test_scaled, y_test))

c:\Users\debna\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:88: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
c:\Users\debna\anaconda3\Lib\site-packages\keras\src\layers\activations\leaky_relu.py:41: UserWarning: Argument `alpha` is deprecated. Use `negative_slope` instead.
  warnings.warn(

Epoch 1/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 3s 20ms/step - accuracy: 0.4650 - loss: 0.7000 - val_accuracy: 0.5714 - val_loss: 0.6890
Epoch 2/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8046 - loss: 0.6662 - val_accuracy: 0.7143 - val_loss: 0.6622
Epoch 3/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.3077 - loss: 0.7747 - val_accuracy: 0.4286 - val_loss: 0.6717
Epoch 4/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5376 - loss: 0.6436 - val_accuracy: 0.4286 - val_loss: 0.6765
Epoch 5/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8298 - loss: 0.5363 - val_accuracy: 0.4286 - val_loss: 0.9150
Epoch 6/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8551 - loss: 0.4999 - val_accuracy: 0.2857 - val_loss: 0.8000
Epoch 7/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8730 - loss: 0.3438 - val_accuracy: 0.4286 - val_loss: 0.8853
Epoch 8/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9111 - loss: 0.3394 - val_accuracy: 0.4286 - val_loss: 0.8841
Epoch 9/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7096 - loss: 0.3650 - val_accuracy: 0.4286 - val_loss: 1.0625
Epoch 10/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9364 - loss: 0.2335 - val_accuracy: 0.5714 - val_loss: 0.9602
Epoch 11/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8801 - loss: 0.2465 - val_accuracy: 0.4286 - val_loss: 1.2190
Epoch 12/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8405 - loss: 0.2551 - val_accuracy: 0.4286 - val_loss: 1.4284
Epoch 13/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9100 - loss: 0.1205 - val_accuracy: 0.5714 - val_loss: 1.3419
Epoch 14/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7729 - loss: 0.2313 - val_accuracy: 0.5714 - val_loss: 1.4411
Epoch 15/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9237 - loss: 0.1151 - val_accuracy: 0.5714 - val_loss: 1.5837
Epoch 16/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.1131 - val_accuracy: 0.5714 - val_loss: 1.7476
Epoch 17/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.0863 - val_accuracy: 0.5714 - val_loss: 1.7271
Epoch 18/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9768 - loss: 0.0897 - val_accuracy: 0.5714 - val_loss: 1.6768
Epoch 19/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9341 - loss: 0.1095 - val_accuracy: 0.5714 - val_loss: 1.5014
Epoch 20/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.0266 - val_accuracy: 0.5714 - val_loss: 1.7012

In [95]:
def predict_output_binary(X_series):
    X_series_scaled = scaler.transform(X_series)
    predictions = model.predict(X_series_scaled)
    binary_predictions = np.round(predictions).astype(int)
    return binary_predictions.flatten()

# Example input series (replace with your own series)
X_series_example = np.array([[1,3,5,7]])

# Predict output for the example input series in binary
predictions_example_binary = predict_output_binary(X_series_example)
print("Predicted output for the example input series (in binary):")
print(predictions_example_binary)

c:\Users\debna\anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step
Predicted output for the example input series (in binary):
[1]

In [103]:
from tensorflow.keras.models import load_model, save_model

# Assuming `model` is your trained Keras model
model.save("my_model.h5")  # Save the model

# Load the model
loaded_model = load_model("my_model.h5")

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.
WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.